# Config file .travis.yml

language: python
sudo: required
cache: pip

python:
  - "2.7"

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - LINT_CHECK="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"

virtualenv:
  system_site_packages: true

install:
  - apt-get -y -q install default-jre ure libreoffice libreoffice-writer libreoffice-core libreoffice-common && apt-get -q -y remove libreoffice-gnome
  - pip install ezodf==0.3.2
  - git clone --depth=1 https://github.com/Elico-Corp/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.1/wkhtmltox-0.12.1_linux-trusty-amd64.deb
  - sudo dpkg -i wkhtmltox-0.12.1_linux-trusty-amd64.deb
  - wkhtmltopdf --version

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
  
